### ISSUE TITLE
command-not-found.sh uses the wrong nix-locate

### ISSUE THREAD

**Issue by barryfm** [nix-community/nix-index-database#110]
Recently I found on nixos-unstable, that the command not found functionality did  not work.

Under zsh, the defined command_not_found_handle() and command_not_found_handler() functions showed:
```
$ type command_not_found_handler
command_not_found_handle is a shell function from /nix/store/cks6ik35l30nkd51dswwan14zyqdkl43-nix-index-with-db-0.1.8/etc/profile.d/command-not-found.sh
$ realpath `which nix-locate`
/nix/store/cks6ik35l30nkd51dswwan14zyqdkl43-nix-index-with-db-0.1.8/bin/nix-locate
```
But the contents of the command-nod-found.sh, shown above gave:
```
attrs=$(/nix/store/v38l3yq312q7d2znwlvzfwfh5zgmz62b-nix-index-0.1.8/bin/nix-locate --minimal --no-group --type x --type s --top-level --whole-name --at-  root "/bin/$cmd")
```

Using a  nix-index rather than a nix-index-db path containing the working nix-locate.

**Comment by Mic92** [comment]
Interesting. Looks different on my machine:

```
% type command_not_found_handler
command_not_found_handler is a shell function from /nix/store/b4i7mjnqx87r0pigfjk6qdm11knvsywp-nix-index-with-db-0.1.8/etc/profile.d/command-not-found.sh
% grep nix-locate /nix/store/b4i7mjnqx87r0pigfjk6qdm11knvsywp-nix-index-with-db-0.1.8/etc/profile.d/command-not-found.sh
    attrs=$(/nix/store/b4i7mjnqx87r0pigfjk6qdm11knvsywp-nix-index-with-db-0.1.8/bin/nix-locate --minimal --no-group --type x --type s --top-level --whole-name --at-root "/bin/$cmd")
```

**Comment by Mic92** [comment]
Does your zshrc contains this?

```
% grep nix-index /etc/zshrc
source /nix/store/b4i7mjnqx87r0pigfjk6qdm11knvsywp-nix-index-with-db-0.1.8/etc/profile.d/command-not-found.sh
```

**Comment by Mic92** [comment]
Do you by chance override `programs.nix-index.package = lib.mkDefault self.packages${pkgs.stdenv.system}.nix-index-with-db;` in your code?

**Comment by barryfm** [comment]
I'm on a x86_64-linux system. I don't do either of the suggested situations.  The package had been working before recently.  The only references I have to nix-index or completion in is the modlules entry:
```
modules = [
  ./configuration.nix
  nix-index-database.nixosModules.nix-index
];
```
and in my configuration:
```
  programs = {
    ## Bash completion (actually default)
    bash.enableCompletion = true;

    ## TRYout zsh
    zsh = {
      enable = true;
      enableBashCompletion = true;
    };

    ## Doesn't work well with flakes
    command-not-found.enable = false;
  };
```
This is all in my /etc/nixos system configuration.  For my user I have a seperate  `~/.config/home-manager` directory for most of my development environment.  But the issue
is present for the root user also.

I tried a nixos-24.05 system I had, where command-not-found.sh worked.  I first
updated the system with nix-index-database pinned to its then current rev
In the flake.nix:
```
    nix-index-database = {
     #url = "github:nix-community/nix-index-database";
      url = "github:nix-community/nix-index-database?rev=4ac3639cebb6286f1a68d015b80e9e0c6c869ce6";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```
After the update, thing were working.  Then I updated again changing the url back to the head, and it stopped working. although nix-locate itself works. The lock file indicated a ref hash of `88ad3d7501e22b2401dd72734b032b7baa794434`.

Having the two `nix-index-with-db` entries in my cache I could see the difference.  The older one had its own copy of `command-not-found.sh` with a the nix-locate reference to the one in its nix-locate command taken from itself.  The newer one was a soft link to the `command-not-found.sh` in the nix-index package.  It also had a `/bin` soft link to nix-index and nix-channel-index in the nix-index store entry that were missing in the older nix-index-with-db.

I could try bisecting to find the release where nix-index-database fails. The git log has a lot of entries between my working and not working setups.  My current workaround is just to use my own edited command-not-found.sh script.

Looking at the package source code I can see that the older (working for me) release
had in nix-index-wrapper.nix the code:
```
  mkdir --parents $out/etc/profile.d
  substitute \
    "${nix-index-unwrapped}/etc/profile.d/command-not-found.sh" \
    "$out/etc/profile.d/command-not-found.sh" \
    --replace "${nix-index-unwrapped}" "$out"
```
which is missing from the current release.

**Comment by Mic92** [comment]
Ok. Given that's fixed now, I would leave it at that and hope everyone affected by that can also just upgraded their system.
