### ISSUE TITLE
Cant proceed

### ISSUE THREAD

**Issue by whoslucifer** [nix-community/nix-index-database#128]
It downloads everythin but stops here.Like its not even doing anything when i check on btop

sudo nixos-rebuild switch --flake .#nix
[sudo] password for asherah: 
building the system configuration...
[1/0/22 built] building index-x86_64-linux:   0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0

**Comment by r-vdp** [comment]
Can you increase the verbosity? I think you can add several `v`s to do so.
