### ISSUE TITLE
Add '/bin' prefix database

### ISSUE THREAD

**Issue by jakobkukla** [nix-community/nix-index-database#130]
I want to use this as command-not-found replacement. As far is I can tell this only provides full database builds. On my system the command-not-found script takes 3s to execute with the full db.

Could we have an option to download and use a prefix filtered db instead like `nix-index --filter-prefix '/bin/'`? Or maybe even have an option to provide both and use the smaller one for the command-not-found script?

**Comment by Mic92** [comment]
How fast is the bin database in comparison? I wonder if nix-index could not somehow compute the smaller database from the bigger one.

**Comment by gvolpe** [comment]
@Mic92 it's significantly faster. Using `nix-index` with the full database is borderline unusable for me; when I type a command not found, it'll take about 2/3 seconds to display the results. Instead, with a smaller database generated via `nix-index --filter-prefix '/bin/'`, the results are displayed immediately.

> Could we have an option to download and use a prefix filtered db instead like nix-index --filter-prefix '/bin/'? Or maybe even have an option to provide both and use the smaller one for the command-not-found script?

It would be great if this could be supported 🙏🏽 

For now, I use a local database, but also with this fork: https://github.com/gvolpe/nix-index/pull/1

**Comment by gvolpe** [comment]
I think I got something working on my fork, happy to upstream these changes: https://github.com/gvolpe/nix-index-database/releases/tag/2024-12-22-163440

Here's how I'm using it: https://github.com/gvolpe/nix-config/commit/da65d6b68c9c88353af1de6df10cfb9341330b5f
