### ISSUE TITLE
Package it to nixpkgs?

### ISSUE THREAD

**Issue by Freed-Wu** [nix-community/nix-index-database#69]
Thank you to create this program which save me about 20 minutes to generate `~/.cache/nix-index/files`! :+1:

Currently, I use this package in `/etc/nixos/configuration.nix` by

```nix
  environment.systemPackages = with pkgs;
    let
      nix-index-database = (
        builtins.getFlake "github:nix-community/nix-index-database"
      ).packages.${builtins.currentSystem}.default;
    in
    [
      nix-index-database
    ];
```

Why not package it to nixpkgs? It can simplify installation:

```nix
  environment.systemPackages = with pkgs;
    [
      nix-index-database
    ];
```

**Comment by Mic92** [comment]
This repo has quite frequent updates. Not sure how we can upstream this into nixpkgs without getting spammy.

**Comment by Freed-Wu** [comment]
> This repo has quite frequent updates

So is it suitable for [NUR](https://github.com/nix-community/nur)?

**Comment by Mic92** [comment]
Yeah. That could be done.

**Comment by Freed-Wu** [comment]
Will it be packaged to your <https://nur.nix-community.org/repos/mic92/>? :smile:

**Comment by Mic92** [comment]
Maybe rather added the repository directly to NUR, I wouldn't want to write an auto-updater for the auto-updater. I currently don't have the need for this to be in NUR, but I would accept pull requests.

**Comment by akaihola** [comment]
@Freed-Wu's snippet works for me, while I couldn't figure out how to use the ones in `README.md`, probably since I haven't [defined my NixOS configuration as a flake](https://nixos.wiki/wiki/Flakes#Using_nix_flakes_with_NixOS).

Maybe include this alternative method of installing `nix-index-database` as well in `README.md`? It would help newbies.

**Comment by Mic92** [comment]
Feel free to add it to the README.

**Comment by Mic92** [comment]
Closing because I currently don't see an option on how to add this to nixpkgs.
