### ISSUE TITLE
The nix-index binary is not exposed and nixpkgs.nix-index cannot be easily installed together with nix-index-database

### ISSUE THREAD

**Issue by e-nikolov** [nix-community/nix-index-database#79]
If I install `nix-index-database` as a home-manager module, I'm missing the `nix-index` binary.

If additionally install `nixpkgs.nix-index`, I get a collision error because both packages create a `command-not-found.sh` script:

```
error: builder for '/nix/store/p66gzj7myjk18avny860d9br5wa4inpz-home-manager-path.drv' failed with exit code 2;
       last 2 log lines:
       > warning: different permissions in `/nix/store/rff42852ldi0cf9qifm7z37ss5kyg8kb-nix-index-0.1.7/etc/profile.d/command-not-found.sh' and `/nix/store/fx3zb44p09j6j3v8rczyvfrrv6k6bfcq-nix-index-with-db-0.1.7/etc/profile.d/command-not-found.sh': 0555 <-> 0444 at /nix/store/dmdx1hna96vlxknnbbp8719j4jz71fp5-builder.pl line 103.
       > error: collision between `/nix/store/fx3zb44p09j6j3v8rczyvfrrv6k6bfcq-nix-index-with-db-0.1.7/etc/profile.d/command-not-found.sh' and `/nix/store/rff42852ldi0cf9qifm7z37ss5kyg8kb-nix-index-0.1.7/etc/profile.d/command-not-found.sh'
       For full logs, run 'nix log /nix/store/p66gzj7myjk18avny860d9br5wa4inpz-home-manager-path.drv'.
error: 1 dependencies of derivation '/nix/store/c84f7q69785071hrpn7ligh2shrilc5m-home-manager-generation.drv' failed to build
```

As a workaround I can create my own derivation on top of `nixpkgs.nix-index` that only copies the `nix-index` binary to /bin:

```nix
    (pkgs.stdenv.mkDerivation {
      name = "nix-index";
      buildInputs = [ pkgs.nix-index-unwrapped ];
      buildCommand = ''
        mkdir -p $out/bin
        cp ${pkgs.nix-index-unwrapped}/bin/nix-index $out/bin/
      '';
    })
```

Is it necessary for `nix-index-with-db` to wrap the `command-not-found.sh` script? The one from `nixpkgs.nix-index` looks the same.

**Comment by Mic92** [comment]
What is your usecase for the nix-index tool when you have a nix index database already? We do not expose it to avoid confusion because nix-locate will no longer respect updates by nix-index.

**Comment by Mic92** [comment]
Closing because of lack of feedback.

**Comment by tobiasBora** [comment]
I was also confused by this but due to a very stupid thing: via nix run, we need to run `nix-index-database yourlibrary`, so we expect this binary to also exist with the module… then, you also try `nix-index yourlibrary`, and this fails… and it is not obvious from the documentation that you actually wrap `nix-locate`. It might be worth adding a line like `You can then call "nix-locate" and it will automatically use the appropriate database`.

**Comment by Mic92** [comment]
Sounds good. Do you want to open a pull request for that?

**Comment by tobiasBora** [comment]
Sure https://github.com/nix-community/nix-index-database/pull/93
